repos:
  # 1. Secret Scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # 2. Standard YAML and whitespace linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: gams-engine/resources/.*
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: gams-engine/templates/ # Helm templates use Go templating which breaks standard YAML parsers

  # 3. Helm Documentation Generation
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --template-files=./README.md.gotmpl

  # 4. Helm Specific Linting (Built-in)
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint

  # 5. Security & Best Practices (Kube-linter)
  - repo: https://github.com/stackrox/kube-linter
    rev: v0.8.2
    hooks:
      - id: kube-linter
