repos:
  # 1. Standard YAML and whitespace linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: gams-engine/resources/.*
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: gams-engine/templates/ # Helm templates use Go templating which breaks standard YAML parsers

  # 2. Helm Specific Linting (Built-in)
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint

  # 3. Security & Best Practices (Kube-linter)
  - repo: https://github.com/stackrox/kube-linter
    rev: v0.6.8
    hooks:
      - id: kube-linter
