{{- if .Values.ingress.enabled -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/name: {{ include "gams-engine.prefixname" . }}-server
    {{- include "gams-engine.labels" . | nindent 4 }}
  name: {{ include "gams-engine.prefixname" . }}-broker
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName:  {{ .Values.ingress.ingressClassName }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ tpl . $ | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ include "gams-engine.prefixname" $ }}-broker
                port:
                  number: 80
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}