apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleaner-deployment
  labels:
    app: cleaner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleaner
  template:
    metadata:
      labels:
        app: cleaner
    spec:
    {{- if .Values.cleaner.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.cleaner.affinity "context" $) | nindent 8 }}
    {{- end }}
      automountServiceAccountToken: false
{{ include "common.images.renderPullSecrets" ( dict "images" (list .Values.cleaner.image) "context" $) | indent 6}}
      containers:
        - name: cleaner
          image: {{ include "common.images.image" (dict "imageRoot" (dict "registry" .Values.cleaner.image.registry "repository" .Values.cleaner.image.repository "tag" (coalesce .Values.cleaner.image.tag .Values.image.tag .Chart.AppVersion)) "global" .Values.global) }}
          imagePullPolicy: Always
          resources:
{{ toYaml .Values.cleaner.resources | indent 12 }}
          env:
            - name: GMS_RUNNER_CLEANER_HEARTBEAT_SEC
              value: "{{ .Values.cleaner.heartbeatSeconds }}"
            - name: GMS_RUNNER_LOG_SHOW_MSEC
              value: "true"
            - name: GMS_RUNNER_DATABASE_NAME
              value: "gamsrest"
{{- if .Values.postgresql.externalDatabase.enabled }}
            - name: GMS_RUNNER_DATABASE_SERVER
              value: "{{ .Values.postgresql.externalDatabase.host }}"
{{- else }}
            - name: GMS_RUNNER_DATABASE_SERVER
              value: database
{{- end }}
            - name: GMS_RUNNER_DATABASE_PORT
              value: "5432"
            - name: GMS_RUNNER_DATABASE_DIALECT
              value: postgresql
            - name: GMS_RUNNER_DATABASE_CLEANER_DRIVER
              value: pg8000
            - name: GMS_RUNNER_DATABASE_CLEANER_USER
              value: "cleaner"
            - name: GMS_RUNNER_DATABASE_CLEANER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_DATABASE_CLEANER_PWD
            - name: GMS_RUNNER_MONGO_HOST
              value: mongo
            - name: GMS_RUNNER_MONGO_INITDB
              value: "gams_worker"
            - name: GMS_RUNNER_MONGO_CLEANER_USER
              value: "jack"
            - name: GMS_RUNNER_MONGO_CLEANER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_MONGO_CLEANER_PWD
            - name: GMS_RUNNER_RABBIT_HOST
              value: queue
            - name: GMS_RUNNER_RABBIT_CLEANER_USER
              value: "cleaner"
            - name: GMS_RUNNER_RABBIT_CLEANER_PWD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_RABBIT_CLEANER_PWD
