apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-cleaner
  labels:
    app:  {{ include "common.names.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "common.names.fullname" . }}-cleaner
  template:
    metadata:
      labels:
        app: {{ include "common.names.fullname" . }}-cleaner
    spec:
    {{- if .Values.global.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.global.nodeSelector "context" $) | nindent 8 }}
    {{- end }}
    {{- if .Values.global.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.global.tolerations "context" $) | nindent 8 }}
    {{- end }}
    {{- if .Values.cleaner.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.cleaner.affinity "context" $) | nindent 8 }}
    {{- end }}
      automountServiceAccountToken: false
{{ include "common.images.renderPullSecrets" ( dict "images" (list .Values.cleaner.image) "context" $) | indent 6}}
      containers:
        - name: cleaner
          image: {{ include "common.images.image" (dict "imageRoot" (dict "registry" .Values.cleaner.image.registry "repository" .Values.cleaner.image.repository "tag" (coalesce .Values.cleaner.image.tag .Values.image.tag .Chart.AppVersion)) "global" .Values.global) }}
          imagePullPolicy: Always
          resources:
{{ toYaml .Values.cleaner.resources | indent 12 }}
          env:
            - name: GMS_RUNNER_CLEANER_HEARTBEAT_SEC
              value: "{{ .Values.config.cleanerHeartbeatSeconds }}"
            - name: GMS_RUNNER_LOG_SHOW_MSEC
              value: "true"
{{- if .Values.postgresql.externalDatabase.enabled }}
            - name: GMS_RUNNER_DATABASE_SERVER
              value: "{{ .Values.postgresql.externalDatabase.host }}"
            - name: GMS_RUNNER_DATABASE_PORT
              value: "{{ .Values.postgresql.externalDatabase.port }}"
{{- else }}
            - name: GMS_RUNNER_DATABASE_SERVER
              value: {{ include "common.names.fullname" . }}-database
            - name: GMS_RUNNER_DATABASE_PORT
              value: "5432"
{{- end }}
            - name: GMS_RUNNER_DATABASE_DIALECT
              value: postgresql
            - name: GMS_RUNNER_DATABASE_NAME
              value: "{{ .Values.postgresql.database }}"
            - name: GMS_RUNNER_DATABASE_CLEANER_DRIVER
              value: pg8000
            - name: GMS_RUNNER_DATABASE_CLEANER_USER
              value: "cleaner"
            - name: GMS_RUNNER_DATABASE_CLEANER_PWD
              valueFrom:
                secretKeyRef:
                  name:  {{ include "common.names.fullname" . }}-gams-secret
                  key: GMS_RUNNER_DATABASE_CLEANER_PWD
            - name: GMS_RUNNER_MONGO_HOST
              value: {{ include "common.names.fullname" . }}-mongo
            - name: GMS_RUNNER_MONGO_INITDB
              value: "gams_worker"
            - name: GMS_RUNNER_MONGO_CLEANER_USER
              value: "jack"
            - name: GMS_RUNNER_MONGO_CLEANER_PWD
              valueFrom:
                secretKeyRef:
                  name:  {{ include "common.names.fullname" . }}-gams-secret
                  key: GMS_RUNNER_MONGO_CLEANER_PWD
            - name: GMS_RUNNER_RABBIT_HOST
              value: {{ include "common.names.fullname" . }}-queue
            - name: GMS_RUNNER_RABBIT_CLEANER_USER
              value: "cleaner"
            - name: GMS_RUNNER_RABBIT_CLEANER_PWD
              valueFrom:
                secretKeyRef:
                  name:  {{ include "common.names.fullname" . }}-gams-secret
                  key: GMS_RUNNER_RABBIT_CLEANER_PWD
