apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gams-engine.name" . }}-mongo-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
data:
  setup.sh: |-
{{ (.Files.Get "resources/mongo/setup.sh") | indent 4 }}
