apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-mongo-config
  namespace: {{ .Release.Namespace }}
data:
  setup.sh: |-
{{ (.Files.Get "resources/mongo/setup.sh") | indent 4 }}
