apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-deployment
  labels:
    app: pgbouncer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
    {{- if .Values.pgBouncer.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.pgBouncer.affinity "context" $) | nindent 8 }}
    {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: engine-pgbouncer
          image: bitnami/pgbouncer:1.19.1
          imagePullPolicy: Always
          resources:
{{ toYaml .Values.pgBouncer.resources | indent 12 }}
          env:
            - name: POSTGRESQL_USERNAME
              value: worker
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_DATABASE_WORKER_PWD
            - name: POSTGRESQL_DATABASE
              value: gamsrest
{{- if .Values.postgresql.externalDatabase.enabled }}
            - name: POSTGRESQL_HOST
              value: "{{ .Values.postgresql.externalDatabase.host }}"
{{- else }}
            - name: POSTGRESQL_HOST
              value: database
{{- end }}
            - name: PGBOUNCER_POOL_MODE
              value: transaction
            - name: PGBOUNCER_DATABASE
              value: gamsrest
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: "5000"
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: "50"
            - name: PGBOUNCER_USERLIST
              valueFrom:
                secretKeyRef:
                  name: gamsworker
                  key: GMS_RUNNER_PGBOUNCER_USERLIST
