apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-database-config
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "resources/postgresql/*").AsConfig . | indent 2 }}
