apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-database-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "resources/postgresql/*").AsConfig . | indent 2 }}
