apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-queue-definition
  namespace: {{ .Release.Namespace }}
data:
  definitions.json: |-
{{ (tpl (.Files.Get "definitions.json") .) | indent 4 }}
