apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gams-engine.name" . }}-queue-def
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
data:
  definitions.json: |-
{{ (tpl (.Files.Get "resources/rabbitmq/definitions.json") .) | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gams-engine.name" . }}-queue-adv-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
data:
  advanced.config: |-
{{ (tpl (.Files.Get "resources/rabbitmq/advanced.config") .) | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gams-engine.name" . }}-queue-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gams-engine.labels" . | nindent 4 }}
data:
  rabbitmq.conf: |-
{{ (tpl (.Files.Get "resources/rabbitmq/rabbitmq.conf") .) | indent 4 }}

